version: '3.8'
services:
  mysql:
    image: mysql
    restart: always
    volumes:
#      - db_data:/var/lib/mysql
      - ./schema/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
#volumes:
#    db_data: